name: test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            compiler: gcc-99
            target: Linux

          - os: macos-latest
            compiler: gcc-99
            target: Macos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run test
        run: ./scripts/test.sh